### ISSUE TITLE
can't create channel from channels page

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/odysee-ios#90]
The page is just blank

**Comment by akinwale** [comment]
I can't seem to reproduce this. Does this happen after you click New Channel? What device are you testing on?

**Comment by tzarebczan** [comment]
![IMG_20210416_105552](https://user-images.githubusercontent.com/8120721/115043315-63221280-9ea2-11eb-8c60-060036d67669.jpg)


Iphone 7

**Comment by akinwale** [comment]
Fixed in https://github.com/lbryio/odysee-ios/commit/71b1fe811fa3bae17bcb1f320f1cf1d6b2bb2c4d.

**Comment by tzarebczan** [comment]
Was still broken in the test flight version. Only shows after creating a channel.
